name: Generate platform strings

on:
  pull_request_target:
    branches: 
      - master
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '11'
        check-latest: true

    - uses: robinraju/release-downloader@v1.3
      with:
        repository: "MixinNetwork/handsaw"
        latest: true
        fileName: "handsaw.zip"

    - uses: montudor/action-zip@v1
      with:
        args: unzip -qq handsaw.zip -d handsaw
    - run: ./handsaw/handsaw/bin/handsaw gen -i ./client -o ./generated

    - name: Commit files
      run: |
        git config --local user.email "touge1027@gmail.com"
        git config --local user.name "tougee"
        git add generated
        git commit -m "Update generated files" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: master